name: Job Profile Auto Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 1-6 * * *'  # every 30 minutes from 1AM to 6AM

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'   # Match your project Java version

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

      - name: Build project
        run: mvn -B clean install

      - name: Run Selenium Tests
        run: mvn test
        env:
          DISPLAY: :99
