name: Job Profile Auto Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 1-6 * * *'

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test
