name: Java Selenium CI

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '30 1 * * *'  # 7:00 AM IST
    - cron: '30 2 * * *'  # 8:00 AM IST
    - cron: '30 3 * * *'  # 9:00 AM IST
    - cron: '30 4 * * *'  # 10:00 AM IST
    - cron: '30 5 * * *'  # 11:00 AM IST
    - cron: '30 6 * * *'  # 12:00 PM IST

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -B

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium tests
        run: mvn test
        env:
          DISPLAY: :99
